const  Data=[{
    id: 1,
    name: 'Dear Zindagi',
    year:2016,
    duration:'2h 31m',
    genre:'Drama,Romance',
    description:'Kaira is a budding cinematographer in search of a perfect life. Her encounter with Jug, an unconventional thinker, helps her gain a new perspective on life. She discovers that happiness is all about finding comfort in life',
    image:'movie-dear-zindagi.png',
    rating:0},
    
    {id: 2,
    name: 'Brave',
    year:2012,
    duration:'1h 33m',
    genre:'Adventurous, comedy',
    description:'Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom. Granted one wish, Merida must rely on her bravery and her archery skills to undo a beastly curse',
    image:'movie-image-Brave.png',
    rating:0},
  
    {id: 3,
    name: 'Moana',
    year:2016,
    duration:'1h 47m',
    genre:'Adventurous, comedy',
    description:'In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana s island, she answers the Ocean s call to seek out the Demigod to set things right',
    image:'image -moana.png',
    rating:0},

    {id: 4,
    name: 'Mulan',
    year:1998,
    duration:'1h 27m',
    genre:'Adventurous, comedy',
    description:'To save her father from death in the army, a young maiden secretly goes in his place and becomes one of China s greatest heroines in the process.',
    image:'image -mulan.png',
    rating:0},

    {id: 5,
    name: 'He Named Me Malala',
    year:2015,
    duration:'1h 28m',
    genre:'Biography,Documentary',
    description:'A look at the events leading up to the Taliban s attack on Pakistani schoolgirl Malala Yousafzai for speaking out on girls education, followed by the aftermath, including her speech to the United Nations.',
    image:'image-he-named-me malala.png',
    rating:0},

    {id: 6,
    name: 'Soul Surfer',
    year:2011,
    duration:'1h 52m',
    genre:'Drama,Biograply,Family',
    description:'Teenage surfer Bethany Hamilton overcomes the odds and her own fears of returning to the water after losing her left arm in a shark attack',
    image:'image -soul-Surfer.png',
    rating:0},

    {id: 7,
    name: 'Bend It Like Beckham',
    year:2002,
    duration:'1h 52m',
    genre:'Comedy,Drama & Romance',
    description:'Two ambitious girls, despite their parents wishes, have their hearts set on careers in professional football.',
    image:'image-Benf it.png',
    rating:0},

    {id:8,
    name:'Into The Wild',
    year:2007,
    duration:'2h 28m',
    genre:'Adventure,Biography,Drama',
    description:'After graduating from Emory University, top student and athlete Christopher McCandless abandons his possessions, gives his entire $24,000 savings account to charity and hitchhikes to Alaska to live in the wilderness. Along the way, Christopher encounters a series of characters that shape his life.',
    image:'image-into-the-wild.png',
    rating:0},

    {id:9,
    name:'The Pursuit Of Happyness',
    year:2006,
    duration:'1h 57m',
    genre:'Drama,Biography',
    description:'A struggling salesman takes custody of his son as he s poised to begin a life-changing professional career.',
    image:'image-the pursuif.png',
    rating:0},

    {id:10,
    name:'Into The Wild',
    year:2007,
    duration:'2h 28m',
    genre:'Adventure,Biography,Drama',
    description:'After graduating from Emory University, top student and athlete Christopher McCandless abandons his possessions, gives his entire $24,000 savings account to charity and hitchhikes to Alaska to live in the wilderness. Along the way, Christopher encounters a series of characters that shape his life.',
    image:'image-the-intouchables.png',
    rating:0
    }];

export default Data;
